# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "binding-ts"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
path = "./lib.rs"

[dependencies]
spire-core = { workspace = true }
